apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: world-service
  template:
    metadata:
      labels:
        app: world-service
    spec:
      containers:
        - name: world-service
          image: harsha9505/world-service:latest
          ports:
            - containerPort: 8082